// Automatic zero-backend fallback for standalone Vercel previews & demo evaluations
export const DEMO_FALLBACK_USERS: Record<string, any> = {
  "aditya.kumar@college.edu": {
    _id: "usr_aditya_1001",
    name: "Aditya Kumar",
    email: "aditya.kumar@college.edu",
    college: "Uttaranchal University",
    department: "CSE",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 42,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80",
    vehicle: { model: "Honda City i-VTEC (Silver)", plateLast4: "4821", type: "car" },
    enrolledIdCardUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
    lastDailyIdCheckDate: "",
  },
  "rahul.sharma@college.edu": {
    _id: "usr_rahul_1002",
    name: "Rahul Sharma",
    email: "rahul.sharma@college.edu",
    college: "Uttaranchal University",
    department: "CSE",
    course: "B.Tech",
    year: 2,
    semester: 4,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 18,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43211"
  },
  "priya.singh@college.edu": {
    _id: "usr_priya_1003",
    name: "Priya Singh",
    email: "priya.singh@college.edu",
    college: "Graphic Era University",
    department: "ECE",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 24,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    vehicle: { model: "Maruti Swift (Red)", plateLast4: "5512", type: "car" },
    enrolledIdCardUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
    lastDailyIdCheckDate: "",
  },
  "admin@campusride.edu": {
    _id: "usr_admin_1000",
    name: "Dean Office & SOC Security",
    email: "admin@campusride.edu",
    college: "Uttaranchal University",
    role: "super_admin",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 0,
    gender: "other",
    avatarURL: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
    phone: "+91 135 277 0000"
  },
  "riya.rawat@geu.ac.in": {
    _id: "usr_riya_1005",
    name: "Riya Rawat",
    email: "riya.rawat@geu.ac.in",
    college: "Graphic Era University",
    department: "CSE",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 31,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43213",
    vehicle: { model: "Hyundai Grand i10 Nios (Polar White)", plateLast4: "8821", type: "car" }
  },
  "pooja.negi@geu.ac.in": {
    _id: "usr_pooja_1006",
    name: "Pooja Negi",
    email: "pooja.negi@geu.ac.in",
    college: "Graphic Era University",
    department: "Management",
    course: "MBA",
    year: 1,
    semester: 2,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 19,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43214",
    vehicle: { model: "Maruti Baleno Alpha (Nexa Blue)", plateLast4: "4410", type: "car" }
  },
  "aarav.bhatnagar@geu.ac.in": {
    _id: "usr_aarav_1007",
    name: "Aarav Bhatnagar",
    email: "aarav.bhatnagar@geu.ac.in",
    college: "Graphic Era University",
    department: "ECE",
    course: "B.Tech",
    year: 4,
    semester: 7,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 38,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43215",
    vehicle: { model: "Honda Amaze (Modern Steel)", plateLast4: "9021", type: "car" }
  },
  "ananya.joshi@geu.ac.in": {
    _id: "usr_ananya_j_1008",
    name: "Ananya Joshi",
    email: "ananya.joshi@geu.ac.in",
    college: "Graphic Era University",
    department: "Computer Applications",
    course: "BCA",
    year: 2,
    semester: 4,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 14,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43216",
    vehicle: { model: "Tata Punch EV (Pristine White)", plateLast4: "1102", type: "car" }
  },
  "simran.kaur@gehu.ac.in": {
    _id: "usr_simran_1009",
    name: "Simran Kaur",
    email: "simran.kaur@gehu.ac.in",
    college: "Graphic Era Hill University",
    department: "Computer Applications",
    course: "BCA",
    year: 2,
    semester: 3,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 22,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43217",
    vehicle: { model: "Tata Tiago EV (Tropical Mist)", plateLast4: "9011", type: "car" }
  },
  "anjali.semwal@upes.ac.in": {
    _id: "usr_anjali_1010",
    name: "Anjali Semwal",
    email: "anjali.semwal@upes.ac.in",
    college: "University of Petroleum and Energy Studies",
    department: "CSE",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 27,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1534751516642-a171edd25218?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43218",
    vehicle: { model: "Hyundai Creta SX (Atlas White)", plateLast4: "8834", type: "car" }
  },
  "pooja.thapa@dit.ac.in": {
    _id: "usr_pooja_t_1011",
    name: "Pooja Thapa",
    email: "pooja.thapa@dit.ac.in",
    college: "DIT University",
    department: "Civil",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 16,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43219",
    vehicle: { model: "Toyota Etios (Classic Silver)", plateLast4: "4490", type: "car" }
  },
  "megha.chauhan@college.edu": {
    _id: "usr_megha_1012",
    name: "Megha Chauhan",
    email: "megha.chauhan@college.edu",
    college: "Uttaranchal University",
    department: "CSE",
    course: "B.Tech",
    year: 3,
    semester: 5,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 33,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43220",
    vehicle: { model: "Tata Altroz XZ (Opera Gold)", plateLast4: "6211", type: "car" }
  },
  "kavita.joshi@geu.ac.in": {
    _id: "usr_kavita_1013",
    name: "Kavita Joshi",
    email: "kavita.joshi@geu.ac.in",
    college: "Graphic Era University",
    department: "Management",
    course: "BBA",
    year: 2,
    semester: 4,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 20,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43221",
    vehicle: { model: "Maruti Brezza (Sizzling Red)", plateLast4: "7721", type: "car" }
  },
  "neha.bisht@geu.ac.in": {
    _id: "usr_neha_b_1014",
    name: "Neha Bisht",
    email: "neha.bisht@geu.ac.in",
    college: "Graphic Era University",
    department: "Computer Applications",
    course: "MCA",
    year: 1,
    semester: 2,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 15,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43222",
    vehicle: { model: "Maruti Swift Dzire (Silky Silver)", plateLast4: "4411", type: "car" }
  },
  "tanya.rawat@geu.ac.in": {
    _id: "usr_tanya_1015",
    name: "Tanya Rawat",
    email: "tanya.rawat@geu.ac.in",
    college: "Graphic Era University",
    department: "Management",
    course: "BBA",
    year: 1,
    semester: 1,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 12,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43223",
    vehicle: { model: "Honda Jazz (Pearl White)", plateLast4: "2233", type: "car" }
  },
  "ayushi.thapliyal@geu.ac.in": {
    _id: "usr_ayushi_1016",
    name: "Ayushi Thapliyal",
    email: "ayushi.thapliyal@geu.ac.in",
    college: "Graphic Era University",
    department: "ECE",
    course: "B.Tech",
    year: 3,
    semester: 5,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 25,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43224",
    vehicle: { model: "Maruti Ciaz (Pearl Sangria Red)", plateLast4: "6677", type: "car" }
  },
  "shruti.bhatt@college.edu": {
    _id: "usr_shruti_1017",
    name: "Shruti Bhatt",
    email: "shruti.bhatt@college.edu",
    college: "Uttaranchal University",
    department: "CSE",
    course: "B.Tech",
    year: 2,
    semester: 4,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 17,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43225",
    vehicle: { model: "Hyundai Venue (Denim Blue)", plateLast4: "5521", type: "car" }
  },
  "divya.panwar@college.edu": {
    _id: "usr_divya_1018",
    name: "Divya Panwar",
    email: "divya.panwar@college.edu",
    college: "Uttaranchal University",
    department: "Management",
    course: "MBA",
    year: 2,
    semester: 4,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 19,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43226",
    vehicle: { model: "Kia Sonet (Gravity Grey)", plateLast4: "8812", type: "car" }
  },
  "priya.negi@upes.ac.in": {
    _id: "usr_priya_n_1019",
    name: "Priya Negi",
    email: "priya.negi@upes.ac.in",
    college: "University of Petroleum and Energy Studies",
    department: "CSE",
    course: "B.Tech",
    year: 4,
    semester: 7,
    role: "student",
    verificationStatus: "verified",
    rating: 5.0,
    totalRides: 28,
    gender: "female",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    avatarURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43227",
    vehicle: { model: "Tata Nexon EV (Teal Blue)", plateLast4: "8899", type: "car" }
  },
  "vikas.dobhal@dit.ac.in": {
    _id: "usr_vikas_1020",
    name: "Vikas Dobhal",
    email: "vikas.dobhal@dit.ac.in",
    college: "DIT University",
    department: "ECE",
    course: "B.Tech",
    year: 3,
    semester: 5,
    role: "student",
    verificationStatus: "verified",
    rating: 4.8,
    totalRides: 30,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43228",
    vehicle: { model: "Volkswagen Polo (Flash Red)", plateLast4: "5544", type: "car" }
  },
  "mayank.semwal@iuu.ac.in": {
    _id: "usr_mayank_1021",
    name: "Mayank Semwal",
    email: "mayank.semwal@iuu.ac.in",
    college: "IMS Unison University",
    department: "Management",
    course: "MBA",
    year: 1,
    semester: 2,
    role: "student",
    verificationStatus: "verified",
    rating: 4.9,
    totalRides: 21,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43229",
    vehicle: { model: "Hyundai Verna (Abyss Black)", plateLast4: "1199", type: "car" }
  },
  "rohit.gairola@college.edu": {
    _id: "usr_rohit_g_1022",
    name: "Rohit Gairola",
    email: "rohit.gairola@college.edu",
    college: "Uttaranchal University",
    department: "Mechanical",
    course: "B.Tech",
    year: 3,
    semester: 6,
    role: "student",
    verificationStatus: "verified",
    rating: 4.7,
    totalRides: 26,
    gender: "male",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    avatarURL: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43230",
    vehicle: { model: "Maruti Suzuki WagonR (Superior White)", plateLast4: "3302", type: "car" }
  }
};

export const DEMO_FALLBACK_RIDES = [
  {
    _id: "ride_uu_00_aditya",
    creator: {
      _id: "usr_aditya_1001",
      name: "Aditya Kumar",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 4.8,
      totalRides: 42,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Honda City i-VTEC (Silver)", plateLast4: "4821" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    departureTime: new Date(Date.now() + 7200000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100,
    matchScore: 98,
    match: {
      isMatch: true,
      matchScore: 0.98,
      percentage: 98,
      breakdown: {
        routeOverlap: 1,
        timeMatch: 1,
        pickupProximity: 1,
        seatBonus: 1,
        detourDistanceKm: 0,
        pickupDistanceKm: 0,
        academicTier: "course_semester",
        academicBonus: 0.12,
        academicPriorityRank: 1,
        academicCompatibilityLabel: "🎓 Same Course & Semester (B.Tech Sem 5)",
        sameCourseAndSemester: true,
        sameDepartment: true,
        sameCollege: true,
      }
    }
  },
  {
    _id: "ride_uu_00_sneha",
    creator: {
      _id: "usr_sneha_1004",
      name: "Sneha Patel",
      college: "Graphic Era University",
      department: "Computer Applications",
      course: "BCA",
      year: 2,
      semester: 3,
      rating: 4.9,
      totalRides: 8,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80"
    },
    vehicle: { type: "car", model: "Maruti Suzuki Swift (Fire Red)", plateLast4: "5512" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    departureTime: new Date(Date.now() + 5400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100,
    matchScore: 94,
    match: {
      isMatch: true,
      matchScore: 0.94,
      percentage: 94,
      breakdown: {
        routeOverlap: 1,
        timeMatch: 1,
        pickupProximity: 1,
        seatBonus: 1,
        detourDistanceKm: 0,
        pickupDistanceKm: 0,
        academicTier: "none",
        academicBonus: 0,
        academicPriorityRank: 4,
        academicCompatibilityLabel: "🌐 Verified Student Commuter",
        sameCourseAndSemester: false,
        sameDepartment: false,
        sameCollege: false,
      }
    }
  },
  {
    _id: "ride_uu_00_aditya_premnagar",
    creator: {
      _id: "usr_aditya_1001",
      name: "Aditya Kumar",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 4.8,
      totalRides: 42,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Honda City i-VTEC (Silver)", plateLast4: "4821" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    departureTime: new Date(Date.now() + 3600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100,
    matchScore: 98,
    match: {
      isMatch: true,
      matchScore: 0.98,
      percentage: 98,
      breakdown: {
        routeOverlap: 1,
        timeMatch: 1,
        pickupProximity: 1,
        seatBonus: 1,
        detourDistanceKm: 0,
        pickupDistanceKm: 0,
        academicTier: "course_semester",
        academicBonus: 0.12,
        academicPriorityRank: 1,
        academicCompatibilityLabel: "🎓 Same Course & Semester (B.Tech Sem 5)",
        sameCourseAndSemester: true,
        sameDepartment: true,
        sameCollege: true,
      }
    }
  },
  {
    _id: "ride_uu_00_tanvi_premnagar",
    creator: {
      _id: "usr_tanvi_1006",
      name: "Tanvi Sharma",
      college: "Uttaranchal University",
      department: "Management",
      course: "MBA",
      year: 1,
      semester: 2,
      rating: 4.9,
      totalRides: 22,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Tata Punch EV (Pristine White)", plateLast4: "8890" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    departureTime: new Date(Date.now() + 7200000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 15,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100,
    matchScore: 96,
    match: {
      isMatch: true,
      matchScore: 0.96,
      percentage: 96,
      breakdown: {
        routeOverlap: 1,
        timeMatch: 1,
        pickupProximity: 1,
        seatBonus: 1,
        detourDistanceKm: 0,
        pickupDistanceKm: 0,
        academicTier: "university",
        academicBonus: 0.05,
        academicPriorityRank: 3,
        academicCompatibilityLabel: "🏛️ Same University (Uttaranchal University)",
        sameCourseAndSemester: false,
        sameDepartment: false,
        sameCollege: true,
      }
    }
  },
  {
    _id: "ride_uu_00_divya_premnagar",
    creator: {
      _id: "usr_divya_1018",
      name: "Divya Panwar",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 2,
      semester: 4,
      rating: 4.95,
      totalRides: 19,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Kia Sonet (Gravity Grey)", plateLast4: "8812" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    departureTime: new Date(Date.now() + 9000000).toISOString(),
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100,
    matchScore: 97,
    match: {
      isMatch: true,
      matchScore: 0.97,
      percentage: 97,
      breakdown: {
        routeOverlap: 1,
        timeMatch: 1,
        pickupProximity: 1,
        seatBonus: 1,
        detourDistanceKm: 0,
        pickupDistanceKm: 0,
        academicTier: "department",
        academicBonus: 0.08,
        academicPriorityRank: 2,
        academicCompatibilityLabel: "📚 Same Department (CSE)",
        sameCourseAndSemester: false,
        sameDepartment: true,
        sameCollege: true,
      }
    }
  },
  {
    _id: "ride_uu_01",
    creator: {
      _id: "usr_aditya_1001",
      name: "Aditya Kumar",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 4.8,
      totalRides: 42,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Honda City i-VTEC (Silver)", plateLast4: "4821" },
    origin: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 3600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 25,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 3,
    routeOverlapPercent: 95
  },
  {
    _id: "ride_uu_02",
    creator: {
      _id: "usr_ananya_1002",
      name: "Ananya Verma",
      college: "Uttaranchal University",
      department: "Management",
      course: "MBA",
      year: 1,
      semester: 1,
      rating: 4.9,
      totalRides: 28,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Hyundai i20 Sportz (Polar White)", plateLast4: "9104" },
    origin: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    destination: { text: "USCS Building (School of Computing Sciences)", lat: 30.3428, lng: 77.9456, coordinates: [77.9456, 30.3428] },
    departureTime: new Date(Date.now() + 1800000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 15,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 1,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_uu_03",
    creator: {
      _id: "usr_meera_1003",
      name: "Meera Nair",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 4.9,
      totalRides: 34,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Kia Sonet Turbo (Gravity Grey)", plateLast4: "6640" },
    origin: { text: "Suddhowala Chowk (Student PG Hub)", lat: 30.3475, lng: 77.9320, coordinates: [77.9320, 30.3475] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 4500000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 2,
    routeOverlapPercent: 96
  },
  {
    _id: "ride_uu_04",
    creator: {
      _id: "usr_rohan_1004",
      name: "Rohan Mehta",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 4.9,
      totalRides: 31,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "bike", model: "Royal Enfield Himalayan", plateLast4: "3218" },
    origin: { text: "Suddhowala Chowk (Student PG Hub)", lat: 30.3475, lng: 77.9320, coordinates: [77.9320, 30.3475] },
    destination: { text: "BBA Building (Uttaranchal Institute of Management)", lat: 30.3420, lng: 77.9461, coordinates: [77.9461, 30.3420] },
    departureTime: new Date(Date.now() + 5400000).toISOString(),
    availableSeats: 1,
    totalSeats: 2,
    pricePerSeat: 15,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 2,
    routeOverlapPercent: 98
  },
  {
    _id: "ride_uu_05",
    creator: {
      _id: "usr_sneha_1005",
      name: "Sneha Patel",
      college: "Graphic Era University",
      department: "Computer Applications",
      course: "BCA",
      year: 2,
      semester: 3,
      rating: 4.95,
      totalRides: 19,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Maruti Swift (Fire Red)", plateLast4: "5512" },
    origin: { text: "Ballupur Chowk (City Entrance)", lat: 30.3395, lng: 78.0125, coordinates: [78.0125, 30.3395] },
    destination: { text: "Campus Gate 1 (Main Entrance, Premnagar Road)", lat: 30.3415, lng: 77.9440, coordinates: [77.9440, 30.3415] },
    departureTime: new Date(Date.now() + 7200000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 35,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 3,
    routeOverlapPercent: 93
  },
  {
    _id: "ride_uu_06",
    creator: {
      _id: "usr_tanvi_1006",
      name: "Tanvi Sharma",
      college: "UPES",
      department: "ECE",
      course: "B.Tech",
      year: 3,
      semester: 5,
      rating: 5.0,
      totalRides: 22,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Tata Punch EV", plateLast4: "8890" },
    origin: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    destination: { text: "BBA Building (Uttaranchal Institute of Management)", lat: 30.3420, lng: 77.9461, coordinates: [77.9461, 30.3420] },
    departureTime: new Date(Date.now() + 6000000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 20,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 3,
    routeOverlapPercent: 94
  },
  {
    _id: "ride_uu_07",
    creator: {
      _id: "usr_kabir_1007",
      name: "Kabir Sharma",
      college: "Uttaranchal University",
      department: "Civil",
      course: "B.Tech",
      year: 4,
      semester: 8,
      rating: 4.95,
      totalRides: 38,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Tata Nexon EV Max", plateLast4: "5019" },
    origin: { text: "Clock Tower (Ghanta Ghar / Paltan Bazaar)", lat: 30.3256, lng: 78.0437, coordinates: [78.0437, 30.3256] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 8400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 50,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 5,
    routeOverlapPercent: 90
  },
  {
    _id: "ride_uu_08",
    creator: {
      _id: "usr_vikram_1008",
      name: "Vikram Malhotra",
      college: "UPES",
      department: "Mechanical",
      course: "B.Tech",
      year: 4,
      semester: 7,
      rating: 4.7,
      totalRides: 25,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Maruti Baleno", plateLast4: "7752" },
    origin: { text: "Vikasnagar Bus Terminal", lat: 30.4350, lng: 77.7710, coordinates: [77.7710, 30.4350] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 9600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 70,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 6,
    routeOverlapPercent: 88
  },
  {
    _id: "ride_uu_09",
    creator: {
      _id: "usr_ananya_1002",
      name: "Ananya Verma",
      college: "Uttaranchal University",
      department: "Management",
      course: "MBA",
      year: 1,
      semester: 1,
      rating: 4.9,
      totalRides: 28,
      gender: "female",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Hyundai i20 Sportz (Polar White)", plateLast4: "9104" },
    origin: { text: "Clock Tower (Ghanta Ghar / Paltan Bazaar)", lat: 30.3256, lng: 78.0437, coordinates: [78.0437, 30.3256] },
    destination: { text: "USCS Building (School of Computing Sciences)", lat: 30.3428, lng: 77.9456, coordinates: [77.9456, 30.3428] },
    departureTime: new Date(Date.now() + 10200000).toISOString(),
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 45,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 4,
    routeOverlapPercent: 91
  },
  {
    _id: "ride_uu_10",
    creator: {
      _id: "usr_aditya_1001",
      name: "Aditya Kumar",
      college: "Uttaranchal University",
      department: "CSE",
      course: "B.Tech",
      year: 3,
      semester: 6,
      rating: 4.8,
      totalRides: 42,
      gender: "male",
      verificationStatus: "verified",
      avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80"
    },
    vehicle: { type: "car", model: "Honda City i-VTEC (Silver)", plateLast4: "4821" },
    origin: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    destination: { text: "Campus Gate 1 (Main Entrance, Premnagar Road)", lat: 30.3415, lng: 77.9440, coordinates: [77.9440, 30.3415] },
    departureTime: new Date(Date.now() + 11400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 55,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 5,
    routeOverlapPercent: 89
  },
  {
    _id: "ride_selaqui_isbt_riya",
    creator: DEMO_FALLBACK_USERS["riya.rawat@geu.ac.in"],
    vehicle: { type: "car", model: "Hyundai Grand i10 Nios (Polar White)", plateLast4: "8821" },
    origin: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 3600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 50,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_selaqui_isbt_pooja",
    creator: DEMO_FALLBACK_USERS["pooja.negi@geu.ac.in"],
    vehicle: { type: "car", model: "Maruti Baleno Alpha (Nexa Blue)", plateLast4: "4410" },
    origin: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 5400000).toISOString(),
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 55,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_selaqui_isbt_aarav",
    creator: DEMO_FALLBACK_USERS["aarav.bhatnagar@geu.ac.in"],
    vehicle: { type: "car", model: "Honda Amaze (Modern Steel)", plateLast4: "9021" },
    origin: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 7200000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 50,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_selaqui_isbt_ananya",
    creator: DEMO_FALLBACK_USERS["ananya.joshi@geu.ac.in"],
    vehicle: { type: "car", model: "Tata Punch EV (Pristine White)", plateLast4: "1102" },
    origin: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 9000000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 45,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_isbt_selaqui_kavita",
    creator: DEMO_FALLBACK_USERS["kavita.joshi@geu.ac.in"],
    vehicle: { type: "car", model: "Maruti Brezza (Sizzling Red)", plateLast4: "7721" },
    origin: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    destination: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    departureTime: new Date(Date.now() + 4500000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 50,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_selaqui_uit_megha",
    creator: DEMO_FALLBACK_USERS["megha.chauhan@college.edu"],
    vehicle: { type: "car", model: "Tata Altroz XZ (Opera Gold)", plateLast4: "6211" },
    origin: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 3000000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 30,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_isbt_campus_anjali",
    creator: DEMO_FALLBACK_USERS["anjali.semwal@upes.ac.in"],
    vehicle: { type: "car", model: "Hyundai Creta SX (Atlas White)", plateLast4: "8834" },
    origin: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    destination: { text: "Campus Gate 1 (Main Entrance, Premnagar Road)", lat: 30.3415, lng: 77.9440, coordinates: [77.9440, 30.3415] },
    departureTime: new Date(Date.now() + 6000000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 50,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_suddhowala_isbt_neha",
    creator: DEMO_FALLBACK_USERS["neha.bisht@geu.ac.in"],
    vehicle: { type: "car", model: "Maruti Swift Dzire (Silky Silver)", plateLast4: "4411" },
    origin: { text: "Suddhowala Chowk (Student PG Hub)", lat: 30.3475, lng: 77.9320, coordinates: [77.9320, 30.3475] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 4800000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 45,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_premnagar_isbt_tanya",
    creator: DEMO_FALLBACK_USERS["tanya.rawat@geu.ac.in"],
    vehicle: { type: "car", model: "Honda Jazz (Pearl White)", plateLast4: "2233" },
    origin: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 5400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 40,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_premnagar_isbt_divya",
    creator: DEMO_FALLBACK_USERS["divya.panwar@college.edu"],
    vehicle: { type: "car", model: "Kia Sonet (Gravity Grey)", plateLast4: "8812" },
    origin: { text: "Premnagar Chowk Market", lat: 30.3340, lng: 77.9620, coordinates: [77.9620, 30.3340] },
    destination: { text: "ISBT Dehradun (Inter-State Bus Terminal)", lat: 30.2885, lng: 78.0080, coordinates: [78.0080, 30.2885] },
    departureTime: new Date(Date.now() + 7200000).toISOString(),
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 40,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_ballupur_campus_ayushi",
    creator: DEMO_FALLBACK_USERS["ayushi.thapliyal@geu.ac.in"],
    vehicle: { type: "car", model: "Maruti Ciaz (Pearl Sangria Red)", plateLast4: "6677" },
    origin: { text: "Ballupur Chowk (City Entrance)", lat: 30.3395, lng: 78.0125, coordinates: [78.0125, 30.3395] },
    destination: { text: "Central Academic Library & Law Block", lat: 30.3425, lng: 77.9450, coordinates: [77.9450, 30.3425] },
    departureTime: new Date(Date.now() + 3600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 30,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_ballupur_campus_vikas",
    creator: DEMO_FALLBACK_USERS["vikas.dobhal@dit.ac.in"],
    vehicle: { type: "car", model: "Volkswagen Polo (Flash Red)", plateLast4: "5544" },
    origin: { text: "Ballupur Chowk (City Entrance)", lat: 30.3395, lng: 78.0125, coordinates: [78.0125, 30.3395] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 6000000).toISOString(),
    availableSeats: 2,
    totalSeats: 4,
    pricePerSeat: 35,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: false },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_suddhowala_campus_shruti",
    creator: DEMO_FALLBACK_USERS["shruti.bhatt@college.edu"],
    vehicle: { type: "car", model: "Hyundai Venue (Denim Blue)", plateLast4: "5521" },
    origin: { text: "Suddhowala Chowk (Student PG Hub)", lat: 30.3475, lng: 77.9320, coordinates: [77.9320, 30.3475] },
    destination: { text: "USCS Building (School of Computing Sciences)", lat: 30.3428, lng: 77.9456, coordinates: [77.9456, 30.3428] },
    departureTime: new Date(Date.now() + 2400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 15,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_suddhowala_campus_simran",
    creator: DEMO_FALLBACK_USERS["simran.kaur@gehu.ac.in"],
    vehicle: { type: "car", model: "Tata Tiago EV (Tropical Mist)", plateLast4: "9011" },
    origin: { text: "Suddhowala Chowk (Student PG Hub)", lat: 30.3475, lng: 77.9320, coordinates: [77.9320, 30.3475] },
    destination: { text: "UIT Building (Uttaranchal Institute of Technology)", lat: 30.3432, lng: 77.9448, coordinates: [77.9448, 30.3432] },
    departureTime: new Date(Date.now() + 3600000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 15,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_clocktower_campus_priya",
    creator: DEMO_FALLBACK_USERS["priya.negi@upes.ac.in"],
    vehicle: { type: "car", model: "Tata Nexon EV (Teal Blue)", plateLast4: "8899" },
    origin: { text: "Clock Tower (Ghanta Ghar / Paltan Bazaar)", lat: 30.3256, lng: 78.0437, coordinates: [78.0437, 30.3256] },
    destination: { text: "BBA Building (Uttaranchal Institute of Management)", lat: 30.3420, lng: 77.9461, coordinates: [77.9461, 30.3420] },
    departureTime: new Date(Date.now() + 5400000).toISOString(),
    availableSeats: 3,
    totalSeats: 4,
    pricePerSeat: 40,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  },
  {
    _id: "ride_vikasnagar_selaqui_pooja",
    creator: DEMO_FALLBACK_USERS["pooja.thapa@dit.ac.in"],
    vehicle: { type: "car", model: "Toyota Etios (Classic Silver)", plateLast4: "4490" },
    origin: { text: "Vikasnagar Bus Terminal", lat: 30.4350, lng: 77.7710, coordinates: [77.7710, 30.4350] },
    destination: { text: "Selaqui Industrial & Institutional Hub", lat: 30.3685, lng: 77.8540, coordinates: [77.8540, 30.3685] },
    departureTime: new Date(Date.now() + 4200000).toISOString(),
    availableSeats: 4,
    totalSeats: 4,
    pricePerSeat: 35,
    status: "active",
    preferences: { musicAllowed: true, smokingAllowed: false, womenOnlyDriver: true },
    recurring: true,
    detourMins: 0,
    routeOverlapPercent: 100
  }
];

export const DEMO_FALLBACK_OPERATIONS = {
  kpis: {
    totalRevenue: 16800,
    totalRides: 14,
    co2SavedKg: 215.4,
    ongoingRidesCount: 15
  },
  pricingConfig: {
    minPricePerSeat: 10,
    basePrice: 15,
    pricePerKm: 4.5,
    localTransitComparison: "Dehradun Vikram shared rate: ₹15–₹20, E-rickshaw: ₹10–₹15",
    updatedBy: "Dean of Student Affairs",
    updatedAt: new Date().toISOString()
  },
  ongoingRides: [
    {
      _id: "ong_01",
      driver: {
        name: "Aditya Kumar",
        avatarURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80",
        institution: "Uttaranchal University",
        college: "Uttaranchal University",
        department: "CSE",
        course: "B.Tech",
        academic: "B.Tech (CSE) • Year 3",
        phone: "+91 98765 43210",
        rating: 4.8,
        vehicle: { model: "Honda City i-VTEC (Silver)", plateLast4: "4821", type: "car" },
        vehicleModel: "Honda City i-VTEC (Silver)",
        vehiclePlate: "4821"
      },
      passengers: [
        { id: "p1", name: "Rahul Sharma", department: "CSE", college: "Uttaranchal University", emergencyContact: { name: "Father", relation: "Parent", phone: "+91 98111 22334" } },
        { id: "p2", name: "Tanvi Sharma", department: "ECE", college: "UPES", emergencyContact: { name: "Mother", relation: "Parent", phone: "+91 98222 33445" } }
      ],
      origin: { text: "Premnagar Chowk Market", coordinates: [77.9620, 30.3340] },
      destination: { text: "UIT Building (Uttaranchal Institute of Technology)", coordinates: [77.9448, 30.3432] },
      pickupPoint: { text: "Premnagar Chowk Market", coordinates: [77.9620, 30.3340] },
      dropPoint: { text: "UIT Building (Uttaranchal Institute of Technology)", coordinates: [77.9448, 30.3432] },
      bridgeVia: "Nanda Ki Chowki Bridge",
      distanceKm: 8.4,
      pricePerSeat: 20,
      totalValue: 40,
      farePerSeat: 20,
      totalCarpoolValue: 40,
      availableSeats: 2,
      departureTime: new Date(Date.now() + 1800000).toISOString(),
      status: "active"
    },
    {
      _id: "ong_02",
      driver: {
        name: "Priya Singh",
        avatarURL: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
        institution: "Uttaranchal University",
        college: "Uttaranchal University",
        department: "ECE",
        course: "B.Tech",
        academic: "B.Tech (ECE) • Year 3",
        phone: "+91 98765 43212",
        rating: 5.0,
        vehicle: { model: "Maruti Swift (Red)", plateLast4: "5512", type: "car" },
        vehicleModel: "Maruti Swift (Red)",
        vehiclePlate: "5512"
      },
      passengers: [
        { id: "p3", name: "Meera Nair", department: "BBA", college: "Uttaranchal University", emergencyContact: { name: "Mother", relation: "Parent", phone: "+91 98333 44556" } }
      ],
      origin: { text: "Suddhowala Chowk (Student PG Hub)", coordinates: [77.9320, 30.3475] },
      destination: { text: "USCS Building (School of Computing Sciences)", coordinates: [77.9456, 30.3428] },
      pickupPoint: { text: "Suddhowala Chowk (Student PG Hub)", coordinates: [77.9320, 30.3475] },
      dropPoint: { text: "USCS Building (School of Computing Sciences)", coordinates: [77.9456, 30.3428] },
      bridgeVia: "Premnagar Flyover",
      distanceKm: 5.2,
      pricePerSeat: 15,
      totalValue: 15,
      farePerSeat: 15,
      totalCarpoolValue: 15,
      availableSeats: 3,
      departureTime: new Date(Date.now() + 2700000).toISOString(),
      status: "active"
    }
  ]
};

export const DEMO_FALLBACK_INCIDENTS = [
  {
    _id: "inc_01",
    tripId: "trip_demo_101",
    reporterId: "usr_priya_1003",
    reporterName: "Priya Singh",
    reporterPhone: "+91 98765 43212",
    incidentType: "route_divergence_warning",
    status: "RESOLVED",
    priority: "MEDIUM",
    location: { text: "Premnagar Flyover Bypass", coordinates: [77.9500, 30.3380] },
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    resolutionNotes: "Route divergence verified by security desk: driver took bypass to avoid road construction."
  }
];

export const DEMO_FALLBACK_VERIFICATIONS = [
  {
    _id: "verif_01",
    user: {
      _id: "usr_rahul_1002",
      name: "Rahul Sharma",
      email: "rahul.sharma@college.edu",
      college: "Uttaranchal University",
      department: "CSE",
      year: 2
    },
    studentIdCardURL: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=400&q=80",
    status: "approved",
    submittedAt: new Date(Date.now() - 86400000).toISOString()
  }
];

export const DEMO_FALLBACK_ANALYTICS = {
  totalEmissionsSavedKg: 215.4,
  totalSharedKilometers: 1260,
  campusTrafficReductionPercent: 24,
  activeVehiclesCount: 8,
  popularCorridors: [
    { corridor: "Premnagar Chowk ⇄ Uttaranchal University", sharePercent: 42 },
    { corridor: "Suddhowala PG Hub ⇄ UIT / USCS Buildings", sharePercent: 35 },
    { corridor: "Selaqui Institutional Hub ⇄ Campus Gate 1", sharePercent: 23 }
  ]
};

export const DEMO_FALLBACK_HUBS = [
  { _id: "hub_01", name: "UIT Building (Uttaranchal Institute of Technology)", code: "UU-UIT", coordinates: [77.9448, 30.3432], activeRidesCount: 4 },
  { _id: "hub_02", name: "USCS Building (School of Computing Sciences)", code: "UU-USCS", coordinates: [77.9456, 30.3428], activeRidesCount: 3 },
  { _id: "hub_03", name: "BBA Building (Uttaranchal Institute of Management)", code: "UU-BBA", coordinates: [77.9461, 30.3420], activeRidesCount: 3 },
  { _id: "hub_04", name: "Central Academic Library & Law Block", code: "UU-LIB", coordinates: [77.9450, 30.3425], activeRidesCount: 2 },
  { _id: "hub_05", name: "Campus Gate 1 (Main Entrance, Premnagar Road)", code: "UU-GATE1", coordinates: [77.9440, 30.3415], activeRidesCount: 5 }
];

export const DEMO_FALLBACK_AUDIT_LOGS = [
  {
    _id: "log_01",
    action: "FARE_POLICY_UPDATE",
    actor: "Dean of Student Affairs",
    details: "Minimum price per seat standard verified at ₹10 per seat.",
    timestamp: new Date().toISOString()
  },
  {
    _id: "log_02",
    action: "STUDENT_VERIFICATION",
    actor: "Campus Registrar",
    details: "Student identity credentials verified for 12 campus commuters.",
    timestamp: new Date(Date.now() - 7200000).toISOString()
  }
];
